// Auto-generated by Wails — do not edit manually.
// This file is replaced when running `wails dev` or `wails generate module`.

'use strict';

// In production these are injected by the Wails v2 runtime as window.go.main.App.*
// During dev/build, these stubs return rejected promises (no runtime available).
function call(name, ...args) {
  const fn = window?.go?.main?.App?.[name];
  if (fn) return fn(...args);
  return Promise.reject(new Error(`Wails runtime not available (${name})`));
}

export const GetConfig = () => call('GetConfig');
export const SaveConfig = (cfg) => call('SaveConfig', cfg);
export const ListOutputFiles = () => call('ListOutputFiles');
export const RunScript = (script, placeCode) => call('RunScript', script, placeCode);
export const StopScript = () => call('StopScript');
export const ReadDemandData = (code) => call('ReadDemandData', code);
export const WriteDemandData = (code, data) => call('WriteDemandData', code, data);
export const GetDataDir = () => call('GetDataDir');
export const OpenOutputFolder = (code) => call('OpenOutputFolder', code);
export const CheckNodeJS = () => call('CheckNodeJS');
export const CheckScriptsSetup = () => call('CheckScriptsSetup');
