// Auto-generated by Wails — do not edit manually.
// This file is replaced when running `wails dev` or `wails generate module`.

'use strict';

const runtime = window.runtime || {};

export const EventsOn = (name, cb) => {
  if (runtime.EventsOn) return runtime.EventsOn(name, cb);
  return () => {};
};
export const EventsOff = (...names) => runtime.EventsOff?.(...names);
export const EventsOnce = (name, cb) => runtime.EventsOnce?.(name, cb);
export const BrowserOpenURL = (url) => runtime.BrowserOpenURL?.(url);
export const WindowMinimise = () => runtime.WindowMinimise?.();
export const WindowMaximise = () => runtime.WindowMaximise?.();
export const WindowClose = () => runtime.WindowClose?.();
export const Quit = () => runtime.Quit?.();
