// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckNodeJS() {
  return window['go']['main']['App']['CheckNodeJS']();
}

export function CheckScriptsSetup() {
  return window['go']['main']['App']['CheckScriptsSetup']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDataDir() {
  return window['go']['main']['App']['GetDataDir']();
}

export function ListOutputFiles() {
  return window['go']['main']['App']['ListOutputFiles']();
}

export function OpenOutputFolder(arg1) {
  return window['go']['main']['App']['OpenOutputFolder'](arg1);
}

export function ReadDemandData(arg1) {
  return window['go']['main']['App']['ReadDemandData'](arg1);
}

export function RunScript(arg1, arg2) {
  return window['go']['main']['App']['RunScript'](arg1, arg2);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function StopScript() {
  return window['go']['main']['App']['StopScript']();
}

export function WriteDemandData(arg1, arg2) {
  return window['go']['main']['App']['WriteDemandData'](arg1, arg2);
}
