// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckNodeJS():Promise<main.Response_main_NodeJSStatus_>;

export function CheckScriptsSetup():Promise<main.Response_bool_>;

export function GetConfig():Promise<main.Response_main_GeneratorConfig_>;

export function GetDataDir():Promise<main.Response_string_>;

export function ListOutputFiles():Promise<main.Response___main_PlaceOutput_>;

export function OpenOutputFolder(arg1:string):Promise<void>;

export function ReadDemandData(arg1:string):Promise<main.Response_main_DemandData_>;

export function RunScript(arg1:string,arg2:string):Promise<void>;

export function SaveConfig(arg1:main.GeneratorConfig):Promise<main.Response_bool_>;

export function StopScript():Promise<void>;

export function WriteDemandData(arg1:string,arg2:main.DemandData):Promise<main.Response_bool_>;
